require 'faraday'

require 'rod/rest/naming'
require 'rod/rest/api'
require 'rod/rest/client'
require 'rod/rest/proxy'
require 'rod/rest/collection_proxy'
require 'rod/rest/constants'
require 'rod/rest/exception'
require 'rod/rest/json_serializer'
require 'rod/rest/metadata'
require 'rod/rest/property_metadata'
require 'rod/rest/resource_metadata'
require 'rod/rest/proxy_factory'
require 'rod/rest/proxy_cache'
